### ISSUE TITLE
Dark window border is missing on legacy theme

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mint-themes-legacy#1]
Hi;

Dark window border is missing on legacy theme. 

![mint-themes-legacy](https://user-images.githubusercontent.com/1300133/144644162-607808df-2e0c-4c86-bbd6-2ca9a429e213.png)

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mint-themes-legacy/commit/e86a214d959ffca2222c73da0676e8510432a3fe
