### ISSUE TITLE
Mint-Y-Legacy window close button is blue instead of green like the rest

### ISSUE THREAD

**Issue by terr72** [linuxmint/mint-themes-legacy#4]
The window close button of Mint-Y-Legacy is blue instead of green like the rest.

**Comment by terr72** [comment]
A screenshot of the discrepancy - GIMP window has blue close button, the other one is green.
This used to be the same before updating to Mint 21.1 Vera.
![mint-theme-discrepancy](https://user-images.githubusercontent.com/23163919/208900104-b117a94a-2ea8-4d8d-a1c6-5fd6b6c54b7e.png)

**Comment by JosephMcc** [comment]
Make sure that you restarted Cinnamon or reboot. Sometimes everything may not update until you do.

**Comment by terr72** [comment]
> If you are using XFCE make sure you choose the right window border theme. Looks like maybe you didn't change that theme as well.

That was exactly the case - I was under the impression that xcfe-appearance-settings would change that as well.
